const A='./assets/';
let projectMenuOpen=false;
const nav=[['dashboard','dashboard.svg','Tổng quan'],['projects','building.svg','Dự án'],['handover','handover.svg','Bàn giao'],['finance','finance.svg','TCKT'],['reports','report.svg','Báo cáo'],['residents','client.svg','Cư dân'],['audit','complain.svg','Góp ý & audit'],['services','service.svg','Dịch vụ'],['orders','work-order.svg','Yêu cầu dịch vụ'],['announcements','announcement.svg','Thông báo']];
const projectRows=[['AQC-ELT','Aqua City - The Elite','Novaland','Nova Service','Biên Hoà, Đồng Nai','Approved','12','1,642','100%','80%'],['AQC-STL','Aqua City - The Stella','Novaland','Nova Service','Đồng Nai','Approved','8','986','76%','68%'],['VLC-01','The Valencia','NovaWorld','PMC','Hồ Chí Minh','Under Approval','6','720','42%','—'],['GVR-01','The Grand Villas','Novaland','Nova Service','Bình Thuận','Approved','18','2,108','95%','74%']];
const unitRows=[['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],['Victoria Village','T4','08','VTV.4-08.02','1PN+','60','Nguyễn Ngọc Thủy','—','Chưa bàn giao','—'],['Victoria Village','T4','32','VTV.4-32.01','Penthouse','200','Ngô Ngọc Thủy','Cho thuê','Đã bàn giao','20/08/2024'],['Victoria Village','T4','00','VTV.4-00.02','Shophouse','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024']];
const importedProductRows=[
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','1PN+','60','Nguyễn Ngọc Thủy','-','Chưa bàn giao','-'],
  ['Victoria Village','T4','32','VTV.4-32.01','Penthouse','200','Ngô Ngọc Thủy','Cho thuê','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','00','VTV.4-00.02','Shophouse','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN+','84','Công ty TNHH Thành Phố Mới','Cho thuê','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Cho thuê','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Để trống','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Để trống','Đã bàn giao','20/08/2024'],
  ['Victoria Village','T4','08','VTV.4-08.02','2PN','72','Nguyễn Ngọc Thủy','Để trống','Đã bàn giao','20/08/2024']
];
const icon=(name,cls='')=>`<img class="${cls}" src="${A}icons/${name}" alt="">`;
function go(r){
  if(r==='login') projectMenuOpen=false;
  if(r==='projects') projectMenuOpen=true;
  location.hash=r;
}
function shell(body,active='dashboard') {const projectArea=['projects','project-detail','buildings','units','unit-detail','import-preview','import-result','create-project','new-project'].includes(active),handoverArea=['handover','handover-detail','handover-team','handover-schedule','handover-email','handover-form','handover-notifications'].includes(active),notificationPage=active==='handover-notifications',detail=active==='project-detail',building=active==='buildings',unitList=active==='units',unitDetail=active==='unit-detail',handoverDetail=['handover-detail','handover-team','handover-schedule','handover-email','handover-form'].includes(active),importPage=active.startsWith('import-')||active==='create-project'||active==='new-project',showProjectSubnav=projectMenuOpen,navActive=projectArea?(building||unitList||unitDetail?'':'projects'):notificationPage?'announcements':handoverArea?'handover':active;return `<div class="app"><aside class="side"><div class="side-logo"><img src="${A}logo-sidebar.png"><img src="${A}sidebar-wordmark.svg"></div><div class="nav-section">${nav.slice(0,1).map(n=>navItem(n,navActive)).join('')}</div><small>BẤT ĐỘNG SẢN</small>${navItem(nav[1],navActive)}${showProjectSubnav?projectSubnav(active):''}${nav.slice(2,5).map(n=>navItem(n,navActive)).join('')}<small>VẬN HÀNH</small>${nav.slice(5).map(n=>navItem(n,navActive)).join('')}<footer>Version 1.0.0<br>© 2026 Novaland Group</footer></aside><div class="workspace"><header class="header"><button class="hamb">${icon('menu.svg')}</button>${projectArea?`<div class="header-crumb"><span>${building?'Dashboard':'Tổng quan'}</span><i>/</i><span>Dự án</span>${detail?'<i>/</i><b>Chi tiết dự án</b>':building?'<i>/</i><b>Phân khu/tháp</b>':unitList||unitDetail?'<i>/</i><b>Sản phẩm</b>':importPage?`<i>/</i><b>${active==='create-project'||active==='new-project'?'Tạo dự án':active==='import-result'?'Kết quả Import':'Preview dữ liệu'}</b>`:''}</div>`:handoverArea?`<div class="header-crumb"><span>Tổng quan</span><i>/</i><span>Bàn giao</span>${notificationPage?'<i>/</i><b>Thông báo bàn giao</b>':handoverDetail?'<i>/</i><b>Chi tiết đợt BG-2026-001</b>':''}</div>`:''}<label class="global-search">${icon('search.svg')}<input placeholder="${handoverArea?'Tìm kiếm mã đợt, tên dự án...':'Search project name, code, investor, ...'}"></label><div class="notify">${icon('notification.svg')}<b>6</b></div><img class="avatar" src="${A}profile.png"><div class="profile"><strong>Kenny Wang</strong><span>${handoverArea&&!handoverDetail?'Business development':'Project Admin'}</span></div></header><main class="main ${detail?'project-detail-main':building?'building-main':unitList?'units-main':unitDetail?'unit-detail-main':importPage?'import-main':handoverArea?'handover-main':projectArea?'projects-main':''}">${body}</main></div></div>`}
function navItem(n,a){const enabled=['dashboard','projects','handover'].includes(n[0]),route=n[0];return `<button class="nav ${a===n[0]?'on':''}"${enabled?` data-go="${route}"`:' aria-disabled="true"'}>${icon(n[1])}<span>${n[2]}</span>${['projects'].includes(n[0])?'<i>⌄</i>':''}</button>`}
function projectSubnav(active){return `<nav class="project-subnav"><button class="${active==='buildings'?'active':''}" data-go="buildings">Phân khu/tháp</button><button class="${active==='units'||active==='unit-detail'?'active':''}" data-go="units">Sản phẩm</button><button>Tài sản & Tiện ích</button></nav>`}
function login(){return `<div class="login"><section class="hero"><div class="login-brand"><img src="${A}logo-login.png"><img src="${A}login-wordmark.svg"></div><h1>One platform. All Operations.</h1><p>Empowering real estate developers and operations teams to<br>manage projects, assets and communities efficiently</p><div class="benefits">${[['project.svg','Project Management','Plan, track and deliver projects with transparency'],['residents.svg','Resident & Communities','Deliver excellent service and engage communities'],['facility.svg','Asset & Facility Management','Manage assets throughout their life cycle and performance'],['insights.svg','Data & insights','Make data driven decision with real-times insights']].map(x=>`<div>${icon(x[0])}<span><b>${x[1]}</b><small>${x[2]}</small></span></div>`).join('')}</div></section><section class="login-side"><div class="language"><span>◎</span><b>Tiếng Việt</b><i>⌄</i></div><form id="login"><header><h2>Chào mừng trở lại !</h2><p>Đăng nhập để truy cập Nova Operation Management Platform</p></header><button type="button" class="ms">${icon('microsoft.svg')}Đăng nhập với Microsoft</button><div class="or"><span>Hoặc đăng nhập</span></div><div class="login-fields">${field('Email','Example@company.com','mail.svg','email')}${field('Mật khẩu','Nhập mật khẩu','lock.svg','password')}<div class="remember"><label><input type="checkbox"> Keep me signed in</label><a>Quên mật khẩu</a></div><button class="submit">${icon('login.svg')}Đăng nhập</button></div></form><footer>${icon('support.svg')}Cần hỗ trợ? Liên hệ <b>Bộ phận IT</b></footer></section></div>`}
function field(label,ph,ic,type){return `<label class="field">${label} <em>*</em><div>${icon(ic)}<input type="${type}" placeholder="${ph}" required>${type==='password'?icon('eye.svg','eye'):''}</div></label>`}
function pageHead(title,sub,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${actions}</div>`}
function controls(){return `<div class="controls"><button>${icon('calendar.svg')}<span>This Month: 1 - 31 May 2024</span><i aria-hidden="true"></i></button><button>${icon('filter.svg')}<span>Bộ lọc</span><i aria-hidden="true"></i></button></div>`}
function stat(label,val,note,ic,color){return `<article class="stat"><div><span>${label}</span><b>${val}</b><small>${note}</small></div><i style="--c:${color}">${icon(ic)}</i></article>`}
function dashboard(investor=false){const stats=investor?[['Total Projects','24','3 Upcoming Handover','building.svg','#29b765'],['Total Investment','24,560','↑ 8.5% vs last month','building.svg','#367cf5'],['Total Units','18,256','↑ 5.4% vs last month','client.svg','#a448e5'],['Total Assets','37,842','↑ 6.7% vs last month','calendar.svg','#ff9300'],['Total Land Bank','312.5','↑ 2.1% vs last month','building.svg','#1da7ba'],['Portfolio Occupancy','78%','↑ 3% vs last month','chart.svg','#078c48']]:[['Dự án của tôi','8','2 Sắp bàn giao','my-project.svg','#2bbd65'],['Tiến độ tổng thể','68%','<mark>+ 6%</mark> so với tháng trước','chart.svg','#087ef5'],['Yêu cầu công việc','324','189 Hoàn thành  ·  95 Đang xử lý','toolbox.svg','#ff8a00'],['Ngân sách so với Thực tế','92%','Theo kế hoạch (128.6B / 118.3B VND)','wallet.svg','#b84df2'],['Sự cố','12','5 Cao  ·  4 Vừa  ·  3 thấp','alert.svg','#ff3b30']];return shell(`${pageHead(investor?'Good morning Kenny Wang!':'Chào Kenny Wang!',investor?"Here's what happen across your project today":'Dưới đây là những gì đã diễn ra trong dự án của bạn ngày hôm nay.',controls())}<section class="stats ${investor?'six':''}">${stats.map(x=>stat(...x)).join('')}</section><section class="dash-grid"><article class="card progress-card"><h3>${investor?'Investment by Project Status':'Tổng quan tiến độ dự án'}</h3>${donut(investor?'24,560':'49',investor?'Billion VND':'Projects','projects')}</article><article class="card trend-card"><h3>${investor?'Investment Trend':'Xu hướng tiến độ'}</h3>${chart()}</article><article class="card orders-card"><h3>${investor?'Investment by Asset Class':'Lệnh công việc theo trạng thái'}</h3>${donut(investor?'24,560':'324',investor?'Billion VND':'Total','orders')}</article>${investor?miniList('Portfolio by Region'):milestones()}${dataCard(investor?'Project Status Overview':'Công việc quá hạn')}${investor?miniList('Financial Summary'):tasks()}</section>`, 'dashboard')}
function donut(v,s,type='projects'){const rows=type==='orders'?[['Completed','189 (58%)'],['In Progress','95 (29%)'],['Overdue','40 (13%)']]:[['Completed','18 (37%)'],['In Progress','21 (43%)'],['At Risk','6 (12%)'],['Not Started','4 (8%)']];return `<div class="donut ${type}"><div><b>${v}</b><small>${s}</small></div><ul>${rows.map(x=>`<li><span>${x[0]}</span><b>${x[1]}</b></li>`).join('')}</ul></div><a>${type==='orders'?'Xem tất cả lệnh công việc':'Xem tất cả dự án'} →</a>`}
function chart(){return `<div class="chart"><div class="chart-legend"><span>This Month</span><span>Last Month</span></div><div class="chart-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><svg viewBox="0 0 600 170" preserveAspectRatio="none"><polyline points="0,120 80,105 150,96 200,70 250,82 320,52 390,37 460,42 530,25 600,5"/><polyline class="dash" points="0,145 80,135 150,112 210,122 280,91 350,99 420,70 500,75 600,52"/><circle cx="320" cy="52" r="5"/></svg><div class="chart-tip"><b>15 May 2024</b><span>This Month: 68%</span><em>Last Month: 54%</em></div><div class="axis"><span>May 1</span><span>May 8</span><span>May 15</span><span>May 22</span><span>May 31</span></div></div>`}
function milestones(){const rows=[['shield.svg','Handover - The Stella','Handover Phase','15'],['milestone-building.svg','Podium Completion - The Elite','Construction Phase','22'],['milestone-eye.svg','Facade Inspection - The Valencia','Quality Check','28'],['flame.svg','Fire System Testing - Grand Villas','MEP Phase','31']];return `<article class="card milestone-card"><h3>Các cột mốc sắp tới ${icon('calendar-clock.svg')}</h3>${rows.map(x=>`<div><i>${icon(x[0])}</i><span><b>${x[1]}</b><small>${x[2]}</small></span><em><b>${x[3]}</b><small>MAY</small></em></div>`).join('')}<a>Xem tất cả các cột mốc →</a></article>`}
function tasks(){const rows=[['Review monthly progress report','Aqua City - The Elite','Hôm nay'],['Approve material submittals','The Valencia','Ngày mai'],['Prepare client meeting presentation','The Grand Villas','16 May'],['Site visit and inspection','The Stella','17 May']];return `<article class="card task-card"><h3>Công việc của tôi ${icon("check-square.svg")}</h3>${rows.map(x=>`<div><i></i><span><b>${x[0]}</b><small>${x[1]}</small></span><em>${x[2]}</em></div>`).join('')}<a>Xem tất cả các công việc →</a></article>`}
function miniList(title){return `<article class="card list"><h3>${title}</h3>${['Aqua City - The Elite','The Stella','The Valencia','Grand Villas'].map((x,i)=>`<div><i>${icon(['shield.svg','milestone-building.svg','milestone-eye.svg','flame.svg'][i])}</i><span><b>${x}</b><small>${['Handover Phase','Construction Phase','Quality Check','MEP Phase'][i]}</small></span><em>${[15,22,28,31][i]} MAY</em></div>`).join('')}<a>View all →</a></article>`}
function dataCard(title){const vi=title==='Công việc quá hạn';return `<article class="card table-mini"><h3>${title}${vi?icon('alert-triangle.svg'):''}</h3><table><thead><tr><th>${vi?'Mã công việc':'Work Order'}</th><th>${vi?'Dự án':'Project'}</th><th>${vi?'Ngày hết hạn':'Due Date'}</th><th>${vi?'Ưu tiên':'Priority'}</th></tr></thead><tbody>${projectRows.map((r,i)=>`<tr><td>WO-2024-${1256-i*67}</td><td>${r[1]}</td><td>02/08/2026</td><td><span>${i<2?'High':'Medium'}</span></td></tr>`).join('')}</tbody></table><a>${vi?'Xem tất cả các công việc quá hạn':'View all'} →</a></article>`}
function listing(type){const cfg=type==='projects'?['Projects','Manage and monitor all real estate projects across developers and property management companies.',projectRows,['Project code','Project','Investor','Ops Entity','Location','Status','Buildings','Units','Handover','Occupancy']]:type==='buildings'?['Buildings','Manage buildings and capacity across every project.',projectRows,['Code','Building','Investor','Ops Entity','Location','Status','Floors','Units','Handover','Occupancy']]:['Handover','Track apartment handovers and readiness status.',projectRows,['Code','Project','Investor','Ops Entity','Location','Status','Buildings','Units','Handover','Occupancy']];return shell(`${pageHead(cfg[0],cfg[1],`<div><button class="ghost">Edit</button><button class="green">＋ Add ${cfg[0]}</button></div>`)}${filters()}${table(cfg[2],cfg[3],type==='projects'?'project':'')}`,type==='handover'?'handover':'projects')}
const buildingRows=[['ELT-A1','Elite - A1','Aqua City','BQL Elite','38','1,642','100%','Operational','10/05/2024'],['ELT-A2','Elite - A2','Aqua City','BQL Elite','32','1,642','100%','Operational','10/05/2024'],['ELT-A3','Elite - A3','Aqua City','BQL Elite','32','1,642','100%','Operational','10/05/2024'],['HOT','Hotel tower','Novaworld - Hồ Tràm','BQL NWHT','12','500','65%','Partial handover','10/05/2025'],['TH8','Townhouse Zone 8','Palm City','-','3','80','-','Planning','-']];
function buildingList(){return shell(`${pageHead('Phân khu/tháp','Xem và quản lý các tòa nhà thuộc một hoặc nhiều dự án.','<div class="building-actions"><button>'+icon('import-upload-dark.svg')+'<span>Import</span></button><button>'+icon('plus.svg')+' Tạo toà mới</button></div>')}<div class="building-filters"><label>${icon('search.svg')}<input placeholder="Tìm kiếm"></label><button>${icon('filter-building.svg')}<span>Tất cả dự án</span></button><button>${icon('filter-ops.svg')}<span>Tất cả BQL</span>${icon('expand-more.svg')}</button><button>${icon('filter-status.svg')}<span>Tất cả trạng thái</span>${icon('expand-more.svg')}</button></div>${buildingTable()}`,'buildings')}
function buildingTable(){return `<article class="building-table"><div><table><thead><tr><th>Mã toà　⌃</th><th>Tên toà　⌃</th><th>Dự án　⌃</th><th>Ban quản lý</th><th>Floors</th><th>Units</th><th>Handover</th><th>Status</th><th>Ngày bàn giao</th><th>Hành động</th></tr></thead><tbody>${buildingRows.map((r,i)=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td><td><b>${r[3]}</b></td><td><b>${r[4]}</b></td><td><b>${r[5]}</b></td><td>${r[6]==='-'?'-':projectProgress(r[6],i===3?'orange':'green')}</td><td><span class="building-status ${i===3?'orange':i===4?'purple':''}">${r[7]}</span></td><td><b>${r[8]}</b></td><td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table></div></article>`}
const pmProjects=[
['AQC-ELT','Aqua City - The Elite','Công ty TNHH Thành Phố Aqua','savills','Biên Hoà, Đồng Nai','Operational','12','1,642','100%','80%'],
['AQC-STL','Aqua City - The Stella','Công ty TNHH Thành Phố Aqua','CBRE','Biên Hoà, Đồng Nai','Operational','10','1,642','100%','85%'],
['AQC-VAL','Aqua City - The Grand Villas','Công ty TNHH Thành Phố Aqua','AQUA','Biên Hoà, Đồng Nai','Operational','-','728','100%','90%'],
['AQC-SUI','Aqua City - The Suite','Công ty TNHH Thành Phố Aqua','PMC','Biên Hoà, Đồng Nai','Partial handover','6','645','82%','32%'],
['NWO-PT','Nova World - Phan Thiết','Công ty TNHH Thành Phố Aqua','JLL','Phan Thiết, Bình Thuận','Operational','12','1,642','100%','80%'],
['NWO-PT','Nova World - Hồ Tràm','Công ty TNHH Thành Phố Aqua','savills','Biên Hoà, Đồng Nai','Partial handover','26','8,620','65%','28%'],
['TGMT','The Grand Manhattan','Công ty TNHH Thành Phố Aqua','MARRIOTT','Bến Thành, Hồ Chí Minh','Constructing','12','1,642','5%','-'],
['SR-RS','Sunrise Riverside','Công ty TNHH Thành Phố Aqua','savills','Bến Thành, Hồ Chí Minh','Operational','12','1,642','100%','80%'],
['EMP-001','Empire City','Công ty TNHH Thành Phố Aqua','savills','Thủ Đức, Hồ Chí Minh','Operational','12','1,642','100%','80%'],
['AQC-ELT','Sunrise City - City View','Công ty TNHH Thành Phố Aqua','savills','Tân Hưng, Hồ Chí Minh','Operational','12','1,642','100%','80%']];
const opsLogoFiles={savills:'savills.png',CBRE:'cbre.png',AQUA:'aqua-japan.png',PMC:'pmc.png',JLL:'jll.png',MARRIOTT:'marriott.png'};
const projectAreas=[['Đồng Nai','Đồng Nai 1'],['Đồng Nai','Đồng Nai 1'],['Đồng Nai','Đồng Nai 1'],['Đồng Nai','Đồng Nai 1'],['Phan Thiết,<br>Bình Thuận','Phan Thiết'],['Đồng Nai','Phan Thiết 1'],['HCM','HCM 1'],['HCM','Tân Hưng'],['Đồng Nai','Thủ Đức,<br>Hồ Chí Minh'],['HCM','Tân Hưng']];
function projectList(){return shell(`${pageHead('Dự án','Quản lý và giám sát tất cả các dự án bất động sản của các chủ đầu tư và công ty quản lý bất động sản.','<div class="project-actions"><button class="edit-project import-project">'+icon('import-upload.svg')+'<span>Nhập dự án</span></button><button class="new-project">'+icon('plus.svg')+' Tạo dự án</button></div>')}<div class="project-filters"><label>${icon('search.svg')}<input placeholder="Từ khóa tìm kiếm"></label>${[['filter-ops.svg','Cao tầng'],['filter-investor.svg','Tất cả CĐT'],['filter-location.svg','Khu vực, vùng'],['filter-status.svg','Tất cả trạng thái']].map(x=>`<button>${icon(x[0])}<span>${x[1]}</span>${icon('expand-more.svg')}</button>`).join('')}</div>${projectTable()}`,'projects')}
function projectTable(){return `<article class="project-table"><div class="project-table-scroll"><table><colgroup><col class="c-code"><col class="c-project"><col class="c-investor"><col class="c-region"><col class="c-zone"><col class="c-status"><col class="c-build"><col class="c-units"><col class="c-progress"><col class="c-progress"><col class="c-action"></colgroup><thead><tr><th>Mã dự án　⌃</th><th>Tên dự án　⌃</th><th>Chủ đầu tư　⌃</th><th>Khu vực</th><th>Vùng</th><th>Trạng thái</th><th>Phân khu/<br>tháp</th><th>Sản<br>phẩm</th><th>Bàn giao</th><th>Tỷ lệ lấp<br>đầy</th><th>Hành<br>động</th></tr></thead><tbody>${pmProjects.map((r,i)=>`<tr data-go="project"><td>${r[0]}</td><td><div class="project-cell">${i<4?`<img src="${A}aqua-city-logo.png">`:`<span class="project-logo">${['NOVA','NOVA','TGM','SUNRISE','EMPIRE','SUNRISE'][i-4]}</span>`}<span><b>${r[1]}</b>${i<4||i===9?'<small>Compound</small>':''}</span></div></td><td>${r[2]}</td><td>${projectAreas[i][0]}</td><td>${projectAreas[i][1]}</td><td><span class="project-status ${r[5].toLowerCase().replace(' ','-')}">${r[5]}</span></td><td><b>${r[6]}</b>${r[6]!=='-'?`<small>${r[6]==='26'?'612':r[6]==='10'?'168':r[6]==='6'?'96':'190'} Floors</small>`:''}</td><td><b>${r[7]}</b>${r[7]==='728'?'<small>Villas</small>':''}</td><td>${projectProgress(r[8],r[8]==='82%'?'orange':'green')}</td><td>${r[9]==='-'?'-':projectProgress(r[9],r[9]==='32%'||r[9]==='28%'?'orange':'green',false)}</td><td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table></div><footer><span>Hiển thị 1-9 trong số 32 dự án</span><nav><b>1</b><span>2</span><span>3</span><span>›</span></nav></footer></article>`}
function projectProgress(v,color,detail=true){return `<div class="project-progress"><b>${v}</b><i><span class="${color}" style="width:${v}"></span></i><small class="${detail?'':'placeholder'}">${detail?'1,642/1,642':'&nbsp;'}</small></div>`}
const importRows=[['1','AQC-NEW','Aqua City - Diamond','Công ty TNHH Thành Phố Aqua','Biên Hoà, Đồng Nai','Hợp lệ'],['2','NWO-BH','Nova World - Bến Hải','Novaland Group','Phan Thiết, Bình Thuận','Hợp lệ'],['3','EMP-02','Empire City Phase 2','Keppel Land','Thủ Đức, HCM','Hợp lệ'],['4','[Trống]','Sunrise Marina','Novaland Group','Thanh Hoá','Thiếu mã dự án'],['5','AQC-ELT','Aqua City - The Elite','Công ty TNHH Thành Phố Aqua','Biên Hoà, Đồng Nai','Mã đã tồn tại']];
function importModal(){return `<div class="import-overlay"><section class="import-modal new-import"><header><h2>Import dự án</h2><button class="close-import">×</button></header><div class="import-modal-body"><label class="import-name"><span class="field-caption">Tên dự án <em>*</em></span><input id="import-name" placeholder="Nhập tên dự án"></label><label class="import-file-title"><span class="field-caption">Tải file <em>*</em></span></label><label class="drop-zone"><input id="excel-file" type="file" accept=".xlsx,.xls,.csv">${icon("upload-cloud.svg")}<b>Kéo thả file hoặc nhấp để tải lên</b><small class="plan-file-name"></small><span>Tối đa 2GB　 Hỗ trợ .xls, .csv　 <u>Tải file mẫu</u></span><button type="button">Chọn file từ máy</button></label></div><footer><button class="close-import">Huỷ</button><button class="continue-import" disabled>Tiếp tục</button></footer></section></div>`}
function formField(label,value,kind='input',required=false,disabled=false){const off=disabled?' disabled':'',area=label.startsWith('Diện tích'),clean=area?value.replace(/\s*m²$/,''):value;return `<label class="${area?'area-field':''}"><span class="field-caption">${label}${required?' <em>*</em>':''}</span>${kind==='select'?`<select${off}><option>${clean}</option></select>`:`<input value="${clean}"${off}>${area?'<i class="area-unit">m<sup>2</sup></i>':''}`}</label>`}
function blankField(label,placeholder,kind='input',required=false){const area=label.startsWith('Diện tích');return `<label class="${area?'area-field':''}"><span class="field-caption">${label}${required?' <em>*</em>':''}</span>${kind==='select'?`<select><option value="">${placeholder}</option></select>`:`<input placeholder="${placeholder}">${area?'<i class="area-unit">m<sup>2</sup></i>':''}`}</label>`}
function createProject(){const rows=importedProductRows;return shell(`<section class="create-project-page"><header><div><h1>Tạo dự án: Aqua City - The Elite</h1><p>Tên file import: <b>Project_import_1208.xlsx</b><i></i><a>Tải lại file</a></p></div><aside><button data-go="projects">←&nbsp; Trở về</button><button class="save-project">${icon("save.svg")}<span>Save</span></button></aside></header><section class="create-card general-form"><h2>Thông tin chung</h2><div class="create-general"><div class="logo-upload"><label>Logo dự án</label><div>${icon("project-logo-placeholder.svg")}</div><button>${icon("import-upload.svg")}<span>Tải logo dự án</span></button></div><div class="form-grid">${formField('Tên dự án','Aqua City - The Elite','input',true)}${formField('Mã dự án (mã SAP)','AQC-ETL','select',true)}${formField('Loại','Cao tầng','select',true)}${formField('Tiến độ dự án','Completed','select',true)}<label class="address-label">Địa chỉ dự án <em>*</em><span><input value="Hương Lộ 2"><select><option>Đồng Nai</option></select><select><option>Biên hoà</option></select></span></label>${formField('Diện tích khu đất','5,0000 m²')}${formField('Diện tích xây dựng','5,0000 m²')}<div class="date-fields">${formField('Ngày bắt đầu xây dựng','20/03/2022')}${formField('Ngày bắt đầu tính phí QL','10/03/2025')}${formField('Ngày bắt đầu DPL','20/03/2022')}${formField('Ngày kết thúc DPL','20/03/2025')}</div></div></div></section><section class="create-card investor-form"><h2>Thông tin chủ đầu tư</h2><div class="investor-form-grid">${formField('Mã số đăng ký kinh doanh','0298798765','select',true)}${formField('Tên doanh nghiệp','Công ty TNHH Thành Phố Qua','select',true,true)}${formField('Ngày cấp','12/02/2014','select',true,true)}${formField('Phát hành bởi','Sở tài Nguyên môi Trường ĐN','select',true,true)}<label class="investor-address">Địa chỉ <em>*</em><span><input value="Hương Lộ 2"><select><option>Đồng Nai</option></select><select><option>Biên hoà</option></select></span></label></div></section>${importProductTable(rows)}<footer class="create-actions"><button data-go="projects">←&nbsp; Trở về</button><button class="save-project">${icon("save.svg")}<span>Save</span></button></footer></section>`,'create-project')}
function newProject(){return shell(`<section class="create-project-page manual-project"><header><div><h1>Tạo dự án</h1></div><aside><button data-go="projects">←&nbsp; Trở về</button><button class="save-project">${icon("save.svg")}<span>Save</span></button></aside></header><section class="create-card general-form"><h2>Thông tin chung</h2><div class="create-general"><div class="logo-upload"><label>Logo dự án</label><div>${icon("project-logo-placeholder.svg")}</div><button>${icon("import-upload.svg")}<span>Tải logo dự án</span></button></div><div class="form-grid">${blankField('Tên dự án','Select Brand','input',true)}${blankField('Mã dự án','Nhập mã dự án','select',true)}${blankField('Loại','Chọn loại dự án','select',true)}${blankField('Tiến độ dự án','Chọn loại','select',true)}<label class="address-label">Địa chỉ dự án <em>*</em><span><input placeholder="Nhập địa chỉ"><select><option>Tỉnh/Thành</option></select><select><option>Phường/xã</option></select></span></label>${blankField('Diện tích khu đất','e.g. 10.000')}${blankField('Diện tích xây dựng','e.g. 20.000')}<div class="date-fields">${blankField('Ngày bắt đầu xây dựng','DD/MM/YYYY')}${blankField('Ngày bắt đầu tính phí QL','DD/MM/YYYY')}${blankField('Ngày bắt đầu DPL','DD/MM/YYYY')}${blankField('Ngày kết thúc DPL','DD/MM/YYYY')}</div></div></div></section><section class="create-card investor-form"><h2>Thông tin chủ đầu tư</h2><div class="investor-form-grid">${blankField('Mã số đăng ký kinh doanh','Nhập mã dự án','select',true)}${blankField('Tên doanh nghiệp','Chọn từ danh sách','select',true)}${blankField('Ngày cấp','Chọn loại dự án','select',true)}${blankField('Phát hành bởi','Chọn loại','select',true)}<label class="investor-address">Địa chỉ <em>*</em><span><input placeholder="Nhập địa chỉ"><select><option>Tỉnh/Thành</option></select><select><option>Phường/xã</option></select></span></label></div></section><section class="create-card manual-products"><h2>Danh sách sản phẩm</h2><label>Tải file <em>*</em></label><label class="manual-drop"><input type="file" accept=".xlsx,.xls,.csv">${icon("upload-cloud.svg")}<b>Kéo thả file hoặc nhấp để tải lên</b><small class="plan-file-name"></small><span>Tối đa 2GB　 Hỗ trợ .xls, .csv　 <u>Tải file mẫu</u></span><button type="button">Chọn file từ máy</button></label></section><footer class="create-actions"><button data-go="projects">←&nbsp; Trở về</button><button class="save-project">${icon("save.svg")}<span>Save</span></button></footer></section>`,'new-project')}
function importProductTable(rows){return `<section class="create-card imported-products"><h2>Danh sách sản phẩm import</h2><p>Sheet sản phẩm　 Tổng hàng: <b>100</b>　 <span>● Valid: 80</span>　 <i>● Error: 5</i>　 <em>● Warning: 5</em></p><div><table><thead><tr>${['Mã SP','Tên dự án','Tháp/khu','Tầng','Loại SP','DT (m²)','Tên chủ hộ','Mục đích SD','Tình trạng BG','Ngày BG'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[3]}</b></td><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[4]}</td><td>${r[5]}</td><td>${r[6]}</td><td><span class="purpose ${r[7]==='Cho thuê'?'p2':r[7]==='Để trống'?'p3':r[7]==='-'?'p1':''}">${r[7]}</span></td><td><span class="handover-state ${r[8]==='Chưa bàn giao'?'off':''}"><i></i>${r[8]}</span></td><td>${r[9]}</td></tr>`).join('')}</tbody></table></div><footer><span>Showing 1-9 of 32 projects</span><nav><b>1</b><span>2</span><span>3</span><span>›</span></nav></footer></section>`}
function importPreview(){return shell(`<section class="import-page"><h1>Preview dữ liệu import</h1><div class="upload-success">☑ File đã tải lên thành công: <b>DuAn_Import_Template.xlsx (45 dòng)</b></div>${importDataTable(true)}<footer><div><span>3 hợp lệ</span><span>1 lỗi</span><span>1 cảnh báo</span></div><aside><button data-go="projects">Quay lại</button><button data-go="import-result">Xác nhận Import</button></aside></footer></section>`,'import-preview')}
function importResult(){return shell(`<section class="import-page result-page"><h1>Kết quả Import dự án</h1><div class="result-success"><i>✓</i><h2>Import thành công!</h2><p>3 dự án đã được thêm mới thành công vào hệ thống.</p></div><div class="result-stats"><div><span>Tổng số dòng</span><b>5</b></div><div><span>Thành công</span><b>3</b></div><div><span>Bỏ qua (trùng mã)</span><b>1</b></div><div><span>Thất bại / Lỗi</span><b>1</b></div></div>${importDataTable(false)}<button class="back-projects" data-go="projects">Về danh sách dự án</button></section>`,'import-result')}
function importDataTable(preview){return `<article class="import-table"><table><thead><tr>${(preview?['STT','Mã dự án','Tên dự án','Chủ đầu tư','Vị trí','Trạng thái kiểm tra']:['Mã dự án','Tên dự án','Kết quả thực hiện']).map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${importRows.map((r,i)=>`<tr>${(preview?r:[r[1]==='[Trống]'?'-':r[1],r[2],r[5]]).map((x,j)=>`<td>${j===(preview?5:2)?`<span class="import-state s${i}">${i<3?'✓ ':i===3?'✕ ':'⚠ '}${preview?x:i<3?'Thành công':i===3?'Lỗi: Thiếu mã dự án':'Bỏ qua: Mã đã tồn tại'}</span>`:x}</td>`).join('')}</tr>`).join('')}</tbody></table></article>`}
const handoverBatches=[['BG-2026-001','Aqua City - The Elite','Sun Harbor 3','120','05/08/2025','Chuẩn bị bàn giao','Nguyễn Văn Minh','12/08/2026'],['BG-2026-002','Aqua City - The Stella','Khu Bắc','32','20/08/2025','Đang bàn giao','Trần Thị Hoa','12/08/2026'],['BG-2026-003','Nova World - Phan Thiết','The Hills','28','25/08/2025','Chờ duyệt KHBG','Lê Hoàng Nam','25/08/2025'],['BG-2026-004','The Grand Manhattan','T1','15','01/09/2025','Lập kế hoạch BG','Phạm Quỳnh Như','01/09/2025'],['BG-2026-005','Palm City','T1','52','15/07/2025','Lập kế hoạch BG','Nguyễn Văn Minh','15/07/2025'],['BG-2026-006','Nova World - Hồ Tràm','Morito','20','01/07/2025','Hoàn thành','Trần Văn Đức','01/07/2025'],['BG-2026-007','Aqua City - The Elite','Ever Green 3','120','20/09/2024','Hoàn thành','Lê Hoàng Nam','20/09/2024'],['BG-2026-008','Palm City','T1','70','10/09/2024','Chuẩn bị bàn giao','Nguyễn Văn Minh','10/09/2024'],['BG-2026-009','Nova World - Hồ Tràm','The Tropicana','65','20/08/2024','Chờ duyệt KHBG','Trần Thị Hoa','20/08/2024'],['BG-2026-010','Nova World - Hồ Tràm','Wonderland','98','05/08/2024','Chuẩn bị bàn giao','Nguyễn Văn Minh','05/08/2024']];
function handoverList(){const action=`<button class="create-handover">${icon('plus.svg')}<span>Lập kế hoạch bàn giao</span></button>`;return shell(`${pageHead('Danh sách đợt bàn giao','Quản lý và theo dõi tất cả các đợt bàn giao căn hộ cho khách hàng',action)}<div class="handover-filters"><label>${icon('search.svg')}<input placeholder="Tìm kiếm từ khoá..."></label><button>${icon('filter-ops.svg')}<span>Tất cả dự án</span>${icon('expand-more.svg')}</button><button>${icon('filter-status.svg')}<span>Trạng thái</span>${icon('expand-more.svg')}</button></div>${handoverBatchTable()}`,'handover')}
function handoverPlanModal(){const projects=['Victoria Village','Aqua City - The Elite','Aqua City - The Stella','Nova World - Phan Thiết','Nova World - Hồ Tràm','The Grand Manhattan','Palm City','Sunrise Riverside','Empire City'];return `<div class="handover-plan-overlay"><section class="handover-plan-modal"><header><h2>Lập kế hoạch bàn giao</h2><button class="close-handover-plan">×</button></header><div class="plan-modal-fields"><label><strong>Tên dự án <em>*</em></strong><select><option value="">Chọn dự án</option>${projects.map(x=>`<option>${x}</option>`).join('')}</select></label><label><strong>Ngày dự kiến bắt đầu bàn giao <em>*</em></strong><span><input class="handover-date-picker" type="date" aria-label="Ngày dự kiến bắt đầu bàn giao">${icon('date-calendar.svg')}</span></label></div><label class="plan-upload-title"><strong>Tải quỹ căn bàn giao <em>*</em></strong></label><label class="plan-drop"><input class="plan-file-input" type="file" accept=".xlsx,.xls,.csv">${icon('upload-cloud.svg')}<b>Kéo thả file hoặc nhấp để tải lên</b><small class="plan-file-name"></small><span>Tối đa 2GB　 Hỗ trợ .xls, .csv　 <a>Tải file mẫu</a></span><button type="button">Chọn file từ máy</button></label><footer><button class="close-handover-plan">Huỷ</button><button class="handover-plan-next">Tiếp tục</button></footer></section></div>`}
const planUnits=[['VTV.4-08.02','08','2PN','72','Nguyễn Ngọc Thuỷ'],['VTV.4-08.02','08','1PN+','60','Nguyễn Ngọc Thuỷ'],['VTV.4-32.01','32','Penhouse','200','Ngô Ngọc Thuỷ'],['VTV.4-00.02','00','Shophouse','72','Nguyễn Ngọc Thuỷ'],['VTV.4-09.05','09','2PN+','84','Công ty TNHH Thanh Phố Mới'],['VTV.4-09.02','09','3PN','90','La Thị Ngọc Nga'],['VTV.4-05.02','05','2PN','72','Trương Minh Hoàng'],['VTV.4-05.12','05','2PN','72','Ngô Trung Hiếu'],['VTV.4-22.04','22','2PN+','72','Bùi Thanh Ngọc'],['VTV.4-22.06','22','2PN','72','Trần Thị Thu Phương'],['VTV.4-23.01','23','2PN','72','Công ty TNHH TM DV Hoàng Ngọc'],['VTV.4-23.05','23','2PN','72','Nguyễn Minh Quân']];
function handoverPlan(){return shell(`<section class="handover-plan-page"><header><h1>Lập kế hoạch bàn giao</h1><aside><button data-go="handover">←&nbsp; Trở về</button><button>${icon('save.svg')}<span>Save</span></button></aside></header><section class="handover-plan-card"><div class="plan-top-fields"><label><strong>Tên dự án <em>*</em></strong><select><option>Victoria Village</option></select></label><label><strong>Ngày bắt đầu bàn giao <em>*</em></strong><span><input value="20/03/2026">${icon('date-calendar.svg')}</span></label><label>Team bàn giao<select><option>Team BG Nguyễn Văn Minh</option></select></label></div><div class="plan-units-head"><div><h2>Quỹ căn bàn giao</h2><p>Tên file import: <b>Project_import_1208.xlsx</b><i></i><a>Tải lại file</a></p></div><p>Tổng hàng: <b>100</b><i></i><span>● Valid: <b>80</b></span><i></i><em>● Error: 5</em><i></i><mark>● Warning: 5</mark></p></div>${handoverPlanTable()}</section></section>`,'handover-detail')}
function handoverPlanTable(){return `<article class="handover-plan-table"><div><table><thead><tr>${['Mã SP','Tên dự án','Tháp/khu','Tầng','Loại SP','DT (m²)','Tên chủ hộ','Ngày dự kiến bàn giao'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${planUnits.map(r=>`<tr><td><b>${r[0]}</b></td><td>Victoria Village</td><td>T4</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>20/03/2026</td></tr>`).join('')}</tbody></table></div><footer><span>Showing 1-9 of 32 projects</span><nav><b>1</b><span>2</span><span>3</span><span>›</span></nav></footer></article>`}
function handoverPlanDetail(){return shell(`<section class="handover-plan-detail-page"><header><div class="plan-detail-title"><h1>Chi tiết kế hoạch bàn giao</h1><span>Chờ duyệt KHBG</span></div><p>Dự án: <b>Victoria Village</b><i></i>Phân khu: <b>T4</b><i></i>Tổng số căn: <b>125</b><i></i>Ngày dự kiến bắt đầu BG: <b>15/08/2026</b></p></header><h3>Quỹ căn bàn giao</h3><div class="plan-detail-layout"><div>${handoverPlanTable()}</div><aside class="approval-card"><h3>Ý kiến phê duyệt</h3><textarea placeholder="Input text"></textarea><label><input type="file" accept=".pdf,.jpg,.jpeg,.png"><u>Upload file</u> <em>(Format: .pdf, .jpg, .png)</em></label><div><button>${icon('reject-circle.svg')}<span>Reject</span></button><button>${icon('approve-check.svg')}<span>Approve</span></button></div><button class="comment-button">${icon('comment-box.svg')}<span>Comment</span></button></aside></div></section>`,'handover-detail')}
function handoverBatchTable(){return `<article class="handover-table batch-list-table"><div><table><thead><tr>${['Mã đợt BG','Tên dự án','Phân khu/Tháp','Tổng số căn','Ngày dự kiến BG','Trạng thái','Leader team BG','Ngày cập nhật','Hành động'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${handoverBatches.map((r,i)=>`<tr data-go="${r[5]==='Chờ duyệt KHBG'?'handover-plan-detail':'handover-detail'}">${r.map((x,j)=>`<td>${j===0?`<b>${x}</b>`:j===5?`<span class="batch-state b${i}">${x}</span>`:x}</td>`).join('')}<td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table></div>${handoverPager('Hiển thị 1-8 trong tổng số 24 đợt bàn giao')}</article>`}
const handoverUnits=[['VTV.1-0801','8','15/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026'],['VTV.1-0802','8','15/08/2024','Đã gửi','Đã thanh toán','17/08/2024','Đã bàn giao','10/08/2026'],['VTV.1-0803','8','15/08/2024','Đã gửi','Đã thanh toán','17/08/2024','Lỗi bàn giao','10/08/2026'],['VTV.1-0804','8','15/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026'],['VTV.1-0912','9','15/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026'],['VTV.1-0910','9','15/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026'],['VTV.1-1005','10','15/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026'],['VTV.1-1008','10','15/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026'],['VTV.1-1012','10','17/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026'],['VTV.1-1212','12','17/08/2024','Đã gửi','-','-','Chưa bàn giao','10/08/2026']];
function handoverDetail(){return shell(`${handoverDetailHead('units')}<div class="handover-detail-tools"><div class="handover-filters detail"><label>${icon('search.svg')}<input placeholder="Tìm kiếm mã căn..."></label><button>${icon('filter-ops.svg')}<span>Trạng thái BG</span>${icon('expand-more.svg')}</button><button>${icon('filter-status.svg')}<span>Tầng</span>${icon('expand-more.svg')}</button></div><aside><div class="batch-menu-wrap"><button class="batch-menu-trigger" data-menu="status">Cập nhật trạng thái ${icon('expand-more.svg')}</button>${statusDropdown()}</div><div class="batch-menu-wrap"><button class="batch-menu-trigger notify-trigger" data-menu="notice">Gửi thông báo ${icon('expand-more.svg')}</button>${noticeDropdown()}</div></aside></div>${handoverUnitTable()}`,'handover-detail')}
function statusDropdown(){return `<div class="batch-dropdown status-dropdown" data-dropdown="status"><section><b><i></i>Thông báo bàn giao</b><button>Chưa gửi</button><button class="selected">Đã gửi</button></section><section><b><i></i>Thanh toán bàn giao</b><button>Đã thanh toán 1 phần</button><button>Đã thanh toán</button></section><section><b><i></i>Bàn giao</b><button>Đã bàn giao</button><button>Lỗi bàn giao</button><button>Bàn giao mặc định</button></section></div>`}
function noticeDropdown(){return `<div class="batch-dropdown notice-dropdown" data-dropdown="notice"><button>Bàn giao lần đầu</button><button class="selected">Bàn giao lần 2</button><button>Bàn giao lần 3</button><button>Hoàn tất sửa chữa</button></div>`}
function handoverDetailHead(tab){return `<section class="handover-detail-head"><div class="handover-title"><h1>Chi tiết đợt bàn giao BG-2024-001</h1><span>Đang thực hiện</span></div><p>Dự án: <b>Aqua City - The Elite</b><i></i>Phân khu: <b>The Elite - T1</b><i></i>Tổng số căn: <b>45</b><i></i>Ngày dự kiến bắt đầu BG: <b>15/08/2026</b></p><aside><button data-go="handover">←&nbsp; Trở về</button><button data-go="create-notification">${icon('plus.svg')}<span>Tạo thông báo</span></button></aside></section><nav class="handover-tabs"><span class="${tab==='units'?'active':''}" data-go="handover-detail">Quỹ căn bàn giao</span><span class="${tab==='team'?'active':''}" data-go="handover-team">Team bàn giao</span><span class="${tab==='schedule'?'active':''}" data-go="handover-schedule">Set lịch bàn giao</span><span class="unavailable-tab" aria-disabled="true">QL lịch đặt hẹn</span><span class="${tab==='email'?'active':''}" data-go="handover-email">Quản lý gửi email</span><span class="${tab==='form'?'active':''}" data-go="handover-form">Biểu mẫu bàn giao</span></nav>`}
function handoverUnitTable(){return `<article class="handover-table detail-table new-detail-table"><div><table><thead><tr><th><input class="select-all-units" type="checkbox" aria-label="Chọn tất cả căn"></th>${['Mã căn','Tên dự án','Phân khu/Tháp','Tầng','Ngày dự kiến bàn giao','Thông báo bàn giao','Thanh toán bàn giao','Ngày hẹn nhận nhà','Trạng thái BG','Ngày cập nhật','Hành động'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${handoverUnits.map((r,i)=>`<tr><td><input class="select-unit" type="checkbox" aria-label="Chọn căn ${r[0]}"></td><td><b>${r[0]}</b></td><td>Aqua City - The Elite</td><td>T1</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="notice-state">${r[3]}</span></td><td class="payment ${r[4]!=='-'?'paid':''}">${r[4]}</td><td>${r[5]}</td><td><span class="detail-bg-state state-${i}"><i></i>${r[6]}</span></td><td>${r[7]}</td><td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table></div>${handoverPager('Hiển thị 1-8 trong tổng số 45 căn hộ')}</article>`}
function handoverPager(text){return `<footer><span>${text}</span><nav><b>1</b><span>2</span><span>3</span><span>›</span></nav></footer>`}
const handoverTeam=[['Nguyễn Văn Minh','Leader','0912 345 678','minh.nv@omp.vn','15','Đang hoạt động'],['Trần Thị Hoa','Nhân viên BG','0908 765 432','hoa.tt@omp.vn','10','Đang hoạt động'],['Lê Hoàng Nam','Nhân viên BG','0977 123 456','nam.lh@omp.vn','10','Đang hoạt động'],['Phạm Quỳnh Như','Nhân viên BG','0965 432 109','nhu.pq@omp.vn','7','Đang hoạt động'],['Võ Thanh Tùng','Kỹ thuật','0934 567 890','tung.vt@omp.vn','-','Đang hoạt động'],['Đặng Minh Tuấn','QC','0901 234 567','tuan.dm@omp.vn','-','Tạm nghỉ']];
function handoverTeamTab(){return shell(`${handoverDetailHead('team')}<div class="team-layout"><section class="team-card"><div class="team-tools"><label>${icon('search.svg')}<input placeholder="Tìm kiếm thành viên..."></label><button>${icon('plus.svg')}<span>Thêm thành viên</span></button></div><article class="team-table"><table><thead><tr>${['STT','Họ và tên','Vai trò','Số điện thoại','Email','Số căn phụ trách','Trạng thái','Hành động'].map(x=>`<th${x==='Số căn phụ trách'||x==='Hành động'?' class="center"':''}>${x==='Số căn phụ trách'?'Số căn<br>phụ trách':x}</th>`).join('')}</tr></thead><tbody>${handoverTeam.map((r,i)=>`<tr><td>${i+1}</td>${r.map((x,j)=>`<td${j===4?' class="center"':''}>${j===0?`<b>${x}</b>`:j===4?`<b>${x}</b>`:j===5?`<span class="member-state ${i===5?'off':''}">${x}</span>`:x}</td>`).join('')}<td class="row-actions"><button class="row-edit">${icon('edit-pencil.svg')}</button><button class="row-delete">${icon('trash.svg')}</button></td></tr>`).join('')}</tbody></table></article></section><aside class="team-summary"><h3>Thống kê phân công</h3><div>${[['Tổng số thành viên','6'],['Đang hoạt động','5'],['Tổng số căn phụ trách','45 / 45'],['Trung bình phụ trách','9 căn/người']].map(x=>`<article><span>${x[0]}</span><b>${x[1]}</b></article>`).join('')}</div></aside></div>`,'handover-detail')}
function handoverScheduleTab(){const slots=[['08:00','09:30'],['10:00','11:30'],['13:30','15:00'],['15:30','17:00']];return shell(`${handoverDetailHead('schedule')}<section class="schedule-card"><h2>Cài đặt lịch bàn giao</h2><div class="schedule-grid"><div class="schedule-col"><h3>Thời gian bàn giao</h3><div class="date-row"><label>Từ ngày<span class="input-icon"><input value="15/08/2024">${icon('date-calendar.svg')}</span></label><label>Đến ngày<span class="input-icon"><input value="30/08/2024">${icon('date-calendar.svg')}</span></label></div><p>Tổng số ngày bàn giao: <b>16 ngày</b> (không tính Chủ nhật)</p><h3>Quy tắc đặt lịch</h3><label class="slot-count">Số ngày tối thiểu đặt trước<input value="2"></label><div class="rule-note">${icon('bell-outline.svg')}<b>Quy tắc đặt lịch trống tối thiểu</b><span>Khách hàng được book lịch nhận nhà sau tối thiểu 2 ngày kể từ ngày nhận thông báo bàn giao nhà.</span><em>Ví dụ: Nếu khách nhận TBBG ngày 15/08, khách chỉ được chọn lịch từ ngày 17/08 trở đi</em></div></div><div class="schedule-col"><h3>Số slot bàn giao / ngày / người</h3><label class="slot-count">Số slot bàn giao tối đa<input value="4"></label><p>Mỗi nhân viên sẽ được phân tối đa 4 slot bàn giao trong 1 ngày</p><div class="slots">${slots.map((x,i)=>`<div><b>Slot ${i+1}:</b><input value="${x[0]}"><input value="${x[1]}"><button>${icon('trash.svg')}</button></div>`).join('')}</div><button class="add-slot">${icon('plus-green.svg')}<span>Thêm khung giờ</span></button><div class="capacity">${icon('info-circle.svg')}<span>Năng lực bàn giao: <b>5 nhân viên × 4 slot × 16 ngày = 320 slot</b> (đủ cho 45 căn)</span></div></div></div><hr><h3>4. Lịch sử cài đặt</h3><table class="schedule-history"><tr><th>Thời gian</th><th>Người thay đổi</th><th>Nội dung thay đổi</th></tr><tr><td>10/08/2024 14:30</td><td>Nguyễn Văn Minh</td><td>Cập nhật thời gian bàn giao: 15/08 - 30/08/2024</td></tr><tr><td>08/08/2024 09:00</td><td>Nguyễn Văn Minh</td><td>Thay đổi số slot từ 3 lên 4 slot/ngày/người</td></tr><tr><td>05/08/2024 16:45</td><td>Trần Thị Hoa</td><td>Tạo mới cài đặt lịch bàn giao</td></tr></table></section><div class="schedule-actions"><button>Huỷ</button><button>Lưu cài đặt</button></div>`,'handover-detail')}
const emailSends=[['BG-2024-001','Thông báo bàn giao','10/08/2024','45','43','2','Hoàn thành'],['BG-2024-001','Nhắc nhở lần 1','13/08/2024','12','12','0','Hoàn thành'],['BG-2024-001','Nhắc nhở lần 2','16/08/2024','5','4','1','Hoàn thành'],['BG-2024-002','Thông báo bàn giao','12/08/2024','32','32','0','Hoàn thành'],['BG-2024-002','Nhắc nhở lần 1','15/08/2024','8','8','0','Hoàn thành'],['BG-2024-003','Thông báo bàn giao','14/08/2024','28','20','8','Đang gửi'],['BG-2024-003','Nhắc nhở lần 1','17/08/2024','8','8','0','Hoàn thành']];
function handoverNotifications(){return shell(`<section class="email-page">${pageHead('Danh sách lần gửi thông báo bàn giao','Quản lý các lần gửi email thông báo bàn giao theo đợt','<button class="create-handover">＋　+ Tạo lần gửi mới</button>')}<div class="handover-filters"><label>${icon('search.svg')}<input placeholder="Tìm kiếm từ khoá..."></label><button>${icon('filter-ops.svg')}<span>Loại thông báo</span>${icon('expand-more.svg')}</button><button>${icon('filter-status.svg')}<span>Trạng thái gửi</span>${icon('expand-more.svg')}</button></div><article class="email-table"><table><thead><tr>${['STT','Mã đợt BG','Loại thông báo','Ngày gửi','Tổng số email','Thành công','Thất bại','Trạng thái','Action'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${emailSends.map((r,i)=>`<tr><td>${i+1}</td>${r.map((x,j)=>`<td>${j===0?`<b>${x}</b>`:j===6?`<span class="email-state ${i===5?'sending':''}">${x}</span>`:x}</td>`).join('')}<td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table>${handoverPager('Hiển thị 1-6 trong tổng số 12 lần gửi')}</article></section>`,'handover-notifications')}
function handoverEmailTab(){return shell(`${handoverDetailHead('email')}<div class="handover-filters"><label>${icon('search.svg')}<input placeholder="Tìm kiếm từ khoá..."></label><button>${icon('filter-ops.svg')}<span>Loại thông báo</span>${icon('expand-more.svg')}</button><button>${icon('filter-status.svg')}<span>Trạng thái gửi</span>${icon('expand-more.svg')}</button></div><article class="email-table"><table><thead><tr>${['STT','Mã đợt BG','Loại thông báo','Ngày gửi','Tổng số email','Thành công','Thất bại','Trạng thái','Action'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${emailSends.map((r,i)=>`<tr><td>${i+1}</td>${r.map((x,j)=>`<td${[3,4,5].includes(j)?' class="center"':''}>${j===0?`<b>${x}</b>`:j===6?`<span class="email-state ${i===5?'sending':''}">${x}</span>`:x}</td>`).join('')}<td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table>${handoverPager('Hiển thị 1-6 trong tổng số 12 lần gửi')}</article>`,'handover-detail')}
const notificationRecipients=[['Nguyễn Văn An','AQ-T1-1201','nguyenvan.an@email.com','0901234567','Email + SMS','Chờ gửi'],['Trần Thị Bình','AQ-T1-1202','tranthi.binh@email.com','0912345678','Email','Đã gửi'],['Lê Hoàng Cường','AQ-T1-1305','lehoang.cuong@email.com','0923456789','Email + SMS + App','Đã gửi'],['Phạm Minh Đức','AQ-T1-1401','phamminh.duc@email.com','0934567890','Email','Lỗi gửi'],['Hoàng Thị Em','AQ-T1-1503','hoangthi.em@email.com','0945678901','SMS','Chờ gửi']];
function createHandoverNotification(){return shell(`<section class="create-notification-page"><header><div><h1>Tạo thông báo bàn giao</h1><p>Đợt bàn giao: <b>Aqua City - The Elite (BG-2024-001)</b></p></div><aside><button data-go="handover-detail">Hủy</button><button>${icon('send.svg')}<span>Gửi thông báo</span></button></aside></header><section class="notification-card notification-content"><div class="notification-card-head"><h2>Nội dung thông báo</h2><label>Chọn template: <select><option>Mẫu thông báo chuẩn đợt 1</option></select></label></div><div class="notification-fields"><label class="notification-title"><span class="notification-caption">Tiêu đề thông báo <em>*</em></span><input value="Thông báo bàn giao căn hộ - Đợt BG-2024-001"></label><label><span class="notification-caption">Loại thông báo <em>*</em></span><select><option>Thông báo bàn giao</option></select></label></div><label class="channel-label"><strong>Kênh gửi <em>*</em></strong><span><i class="checked">✓</i>Email</span><span><i class="checked">✓</i>SMS</span><span><i></i>App notification</span></label><label class="editor-label">Nội dung chi tiết <em>*</em><div class="notification-editor"><nav class="editor-toolbar"><button class="tool-bold">B</button><button class="tool-italic">I</button><button class="tool-underline">U</button><i></i><button>${icon("editor-bullets.svg")}</button><button>${icon("editor-numbered.svg")}</button><i></i><button>${icon("editor-link.svg")}</button><button>${icon("editor-image.svg")}</button></nav><div contenteditable="true"><p>Kính gửi Quý khách hàng,</p><p>Chúng tôi trân trọng thông báo lịch bàn giao căn hộ thuộc dự án Aqua City - The Elite như sau:</p><p>- Thời gian: <b>[Ngày bàn giao]</b><br>- Địa điểm: <b>[Địa chỉ dự án]</b><br>- Căn hộ: <b>[Mã căn hộ]</b></p><p>Quý khách vui lòng mang theo CMND/CCCD và hợp đồng mua bán để hoàn tất thủ tục.</p><p>Trân trọng,<br>Ban Quản lý Dự án OMP</p></div></div></label></section>${notificationRecipientsTable()}</section>`,'handover-detail')}
function notificationRecipientsTable(){return `<section class="notification-card recipients-card"><header><h2>Danh sách người nhận <span>45 người</span></h2><aside><button>${icon('plus-green.svg')} Thêm người nhận</button><label>${icon('search.svg')}<input placeholder="Tìm họ tên, căn hộ..."></label></aside></header><div class="recipients-scroll"><table><thead><tr><th><i class="recipient-check checked">✓</i></th><th>STT</th><th>Họ và tên</th><th>Mã căn hộ</th><th>Email</th><th>Số điện thoại</th><th>Kênh gửi</th><th>Trạng thái</th><th>Action</th></tr></thead><tbody>${notificationRecipients.map((r,i)=>`<tr><td><i class="recipient-check ${i===3?'':'checked'}">${i===3?'':'✓'}</i></td><td>${i+1}</td><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td><span class="recipient-state s${i}">${r[5]}</span></td><td>${icon('view.svg')}${icon('edit-simple.svg')}${i===3?icon('retry.svg'):''}</td></tr>`).join('')}</tbody></table></div><footer><span>Hiển thị 1-5 trong tổng số 45 người nhận</span><nav>‹ <b>1</b> 2 3 ›</nav></footer></section>`}
const handoverForms=[[1,'BM-001','Biên bản bàn giao căn hộ','10/08/2024'],[2,'BM-002','Biên bản bàn giao shophouse','12/08/2024'],[3,'BM-003','Biên bản bàn giao Penhouse','15/08/2024'],[4,'BM-004','Thông báo bàn giao','20/08/2024'],[5,'BM-005','Thông báo nhắc bàn giao lần 1','22/08/2024'],[6,'BM-006','Thông báo nhắc bàn giao lần 2','25/08/2024'],[7,'BM-007','Bàn giao tự động','25/08/2024'],[7,'BM-007','Bàn giao tự động','25/08/2024']];
function handoverFormTab(){return shell(`${handoverDetailHead('form')}<article class="handover-table form-table"><div><table><thead><tr>${['STT','Mã biểu mẫu','Tên biểu mẫu','Ngày tạo','Trạng thái','Hành động'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${handoverForms.map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td><td>${r[3]}</td><td><span class="member-state">Đang sử dụng</span></td><td class="form-action-cell"><div class="form-actions">${icon('view.svg')}<a>In mẫu</a></div></td></tr>`).join('')}</tbody></table></div></article>`,'handover-detail')}
function filters(){return `<div class="filters"><label>${icon('search.svg')}<input placeholder="Search..."></label><button>▥ Investor　⌄</button><button>◉ Status　⌄</button><button>⌖ Location　⌄</button></div>`}
function table(rows,heads,to=''){return `<article class="data"><div class="scroll"><table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}<th>Action</th></tr></thead><tbody>${rows.concat(rows).map(r=>`<tr ${to?`data-go="${to}"`:''}>${r.map((x,i)=>`<td>${i===5?`<span class="badge">${x}</span>`:i===1?`<b>${x}</b>`:x}</td>`).join('')}<td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table></div><footer>Showing 1-8 of 32 projects <span><b>1</b>　2　3　›</span></footer></article>`}
const allUnits=[['VTV.4-08.02','Victoria Village','T4','08','2PN','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],['VTV.4-08.02','Victoria Village','T4','08','1PN+','60','Nguyễn Ngọc Thủy','-','Chưa bàn giao','-'],['VTV.4-32.01','Victoria Village','T4','32','Penhouse','200','Ngô Ngọc Thủy','Cho thuê','Đã bàn giao','20/08/2024'],['VTV.4-00.02','Victoria Village','T4','00','Shophouse','72','Nguyễn Ngọc Thủy','Cư trú','Đã bàn giao','20/08/2024'],['VTV.4-08.02','Victoria Village','T4','08','2PN+','84','Công ty TNHH Thành Phố Mới','Cho thuê','Đã bàn giao','20/08/2024'],...Array.from({length:7},(_,i)=>['VTV.4-08.02','Victoria Village','T4','08','2PN','72','Nguyễn Ngọc Thủy',i<4?'Cư trú':'Để trống','Đã bàn giao','20/08/2024'])];
function units(){return shell(`${pageHead('Sản phẩm','Xem và quản lý thông tin sản phẩm')}<div class="unit-filters"><label>${icon('search.svg')}<input placeholder="Tìm kiếm"></label><button>${icon('filter-building.svg')}<span>Tất cả dự án</span></button><button>${icon('filter-ops.svg')}<span>Tất cả BQL</span>${icon('expand-more.svg')}</button><button>${icon('filter-status.svg')}<span>Tất cả trạng thái</span>${icon('expand-more.svg')}</button></div>${unitTable()}`,'units')}
function unitTable(){return `<article class="unit-table"><div><table><thead><tr>${['Mã SP','Tên dự án','Tháp/khu','Tầng','Loại SP','DT (m²)','Tên chủ hộ','Mục đích SD','Tình trạng BG','Ngày BG','Hành động'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${allUnits.map((r,i)=>`<tr data-go="unit"><td><b>${r[0]}</b></td>${r.slice(1,7).map(x=>`<td>${x}</td>`).join('')}<td><span class="use-tag ${r[7]==='Cho thuê'?'rent':r[7]==='Để trống'?'empty':''}">${r[7]}</span></td><td><span class="handover-state ${r[8]==='Chưa bàn giao'?'waiting':''}">${r[8]}</span></td><td>${r[9]}</td><td>${icon('view.svg')}</td></tr>`).join('')}</tbody></table></div><footer><span>Showing 1-9 of 32 projects</span><nav><b>1</b><span>2</span><span>3</span><span>›</span></nav></footer></article>`}
function projectDetail(){return shell(`<section class="project-detail-head"><div class="detail-logo"><img src="${A}aqua-city-logo.png"></div><div><span class="project-status">Operational</span><h1>Aqua City - The Elite <i>☆</i></h1><p>Mã dự án: <b>AQC-ETL</b><em></em><span class="project-location">${icon("project-location.svg")}Biên hoà, Đồng Nai</span> <em></em>Chủ đầu tư: <strong>Công ty TNHH Thành Phố Aqua</strong></p></div><aside><button data-go="projects">←&nbsp; Trở về</button><button>${icon("edit-project.svg")}<span>Chỉnh sửa dự án</span></button></aside></section><nav class="project-tabs">${['Thông tin chung','Tháp/khu','SP','Tài sản & CSVC','Tài liệu','Bàn giao','Team dự án','ĐV vận hành','Khoản mục tính phí','Lịch sử'].map((x,i)=>`<span class="${i?'':'active'}">${x}</span>`).join('')}</nav><section class="project-detail-grid"><div class="detail-left">${detailInfo()}${investorInfo()}${activityCard()}</div><aside class="detail-right">${summaryCard()}${contactsCard()}</aside></section>`,'project-detail')}
function detailCard(title,body,cls=''){return `<article class="detail-card ${cls}"><h3>${title}<span>⌃</span></h3>${body}</article>`}
function detailInfo(){const rows=[['Dự án','Aqua City - The Elite'],['Địa chỉ dự án','Hương Lộ 2, xã Long Hưng, TP Biên Hòa, Tỉnh Đồng Nai, Việt Nam'],['Mã dự án','AQC-ETL'],['Tiến độ dự án','Completed'],['Diện tích khu đất (m²)','5,000.00'],['Diện tích xây dựng (m²)','7,000.00'],['Ngày bắt đầu xây dựng','02/08/2021'],['Ngày bắt đầu tính phí QL','02/08/2022'],['DPL start date','02/03/2023'],['DPL Expired date <small>(common area)</small>','28/03/2028']];return detailCard('Thông tin chung',`<div class="detail-fields">${rows.map(x=>`<div><label>${x[0]}</label><b>${x[1]}</b></div>`).join('')}</div>`,'general-info')}
function investorInfo(){const rows=[['Tên','Công ty TNHH Thành Phố Aqua'],['Địa chỉ','Hương Lộ 2, xã Long Hưng, TP Biên Hòa, Tỉnh Đồng Nai, Việt Nam'],['Mã số đăng ký kinh doanh','098978655'],['Ngày cấp','12/02/2014'],['Phát hành bởi','Sở Tài Nguyên Môi Trường ĐN']];const bank=[['Tên tài khoản','Công ty TNHH Thành Phố Aqua'],['Số tài khoản','0987 8897 9900 0000'],['Tên ngân hàng -Chi nhánh','VP Bank - CN Hồ Chí Minh']];return detailCard('Thông tin chủ đầu tư',`<div class="investor-fields">${rows.map(x=>`<div><label>${x[0]}</label><b>${x[1]}</b></div>`).join('')}</div><h4>Thông tin ngân hàng</h4><div class="bank-fields">${bank.map(x=>`<div><label>${x[0]}</label><b>${x[1]}</b></div>`).join('')}</div>`,'investor-info')}
function activityCard(){const rows=[['activity-handover.svg','Handover to unit ETL-12A-0801','unit ETL-12A-0801','LT','Lê Thu Thủy','Hoàn thành'],['activity-workorder.svg','Work order WO-2026-1256 completed,','Building A2','LB','Lê Quốc Bảo','Hoàn thành'],['activity-resident.svg','New resident registered','Resident Ngô Minh Trang','LT','Phan Thị Thuỷ','Hoàn thành'],['activity-asset.svg','Asset AS-000812 maintenance','Lift-A2-01','TT','Trần Kim Thanh','Đang xử lý'],['activity-report.svg','Monthly operation report - Jul 2026','Operations','NM','Nguyễn Hoàng Nam','Hoàn thành']];return detailCard('Các hoạt động gần đây',`<table class="activity-table"><thead><tr><th>Hoạt động</th><th>Liên quan tới</th><th>Tạo bởi</th><th>Ngày tạo</th><th>Trạng thái</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${icon(x[0])}<span>${x[1]}</span></td><td>${x[2]}</td><td><i class="person p${i}">${x[3]}</i>${x[4]}</td><td>12/08/2026</td><td><span class="activity-status ${x[5]==='Hoàn thành'?'':'doing'}">${x[5]}</span></td></tr>`).join('')}</tbody></table><a>View all activities　→</a>`,'activity-card')}
function summaryCard(){const rows=[['Số tháp','2'],['Số tầng','34 ( + 1 tầng KT,<br>1 tầng áp mái)'],['TMDV/Shophouse (căn)','20'],['Office (căn)','33'],['Căn hộ (căn)','1028'],['Bãi xe hơi B1, B2 (chỗ)','172'],['Bãi xe máy B1, B2 (chỗ)','3,879'],['Phòng SH cộng đồng','2'],['Hồ bơi','2'],['Phòng Kids','2'],['Sân tennis','1']];return detailCard('Tóm tắt',`<div class="summary-list">${rows.map(x=>`<p><span>${x[0]}</span><b>${x[1]}</b></p>`).join('')}</div>`,'summary-card')}
function contactsCard(){const rows=[['Project manager','NP','Nguyễn Thanh Phương','thanh.pn@novaland.vn'],['Operation Manager','NP','Nguyễn Thanh Phương','thanh.pn@novaland.vn'],['Office manager','NP','Nguyễn Thanh Phương','thanh.pn@novaland.vn']];return detailCard('Người liên hệ dự án',`${rows.map((x,i)=>`<div class="contact"><h4>${x[0]}</h4><div><i class="contact-avatar c${i}">${x[1]}</i><span><b>${x[2]}</b><small>${x[3]}</small></span><em>${icon("contact-mail.svg")}${icon("contact-phone.svg")}</em></div></div>`).join('')}<a>Xem toàn bộ thành viên　→</a>`,'contacts-card')}
function infoCard(t,rows){return `<article class="card info"><h3>${t}</h3>${rows.map(x=>`<p><span>${x[0]}</span><b>${x[1]}</b></p>`).join('')}</article>`}
function progressCard(){return `<article class="card info"><h3>Project progress</h3>${[['Handover rate','100%'],['Occupancy rate','80%']].map(x=>`<p><span>${x[0]}</span><b>${x[1]}</b></p><i><b style="width:${x[1]}"></b></i>`).join('')}<aside>ⓘ Project is operating stably and has reached maximum handover.</aside></article>`}
function unitDetail(){return shell(`<section class="unit-title"><div><h1>Chi tiết sản phẩm VTV.4-0802 <span>${icon("double-check.svg")}Đã bàn giao</span></h1><p>Quản gia: <b>Hoàng Minh Thư</b></p></div><button data-go="units">←&nbsp; Back</button></section><div class="unit-warning"><b>${icon("warning-solid.svg")}Hợp đồng thuê của cư dân Phạm Thùy Linh sắp hết hạn</b><span>Vui lòng liên hệ Chủ hộ để cập nhật thông tin　<a>Cập nhật hợp đồng thuê</a></span><i>×</i></div><nav class="unit-tabs">${['Thông tin cơ bản','Bàn giao','Chủ sở hữu','Cư dân','Thông tin thuê','Tài liệu căn hộ','Yêu cầu dịch vụ','Ghi chú','Phí & Công nợ','Lịch sử'].map((x,i)=>`<span class="${i?'':'active'}">${x}</span>`).join('')}</nav><div class="unit-detail-grid"><main>${unitBasic()}${unitHandover()}${unitOwners()}${simpleUnitTable('Chính sách bán hàng',[['P_QLY','04','29/09/2025, 21:00','24'],['P_QLY_XE','04','23/09/2025, 15:45','2'],['P_VS','01','24/09/2025, 16:15','12']])}${unitSection('Cư dân','')} ${unitRentals()}${unitDocuments()}${unitServices()}${unitSection('Phí & Công nợ','')}${unitSection('Ghi chú','')}</main>${unitHistory()}</div>`,'unit-detail')}
function unitSection(title,body){return `<article class="unit-section ${body?'':'collapsed'}"><h3>${title}<span aria-hidden="true"></span></h3>${body}</article>`}
function unitBasic(){return unitSection('Thông tin sản phẩm',`<div class="unit-fields">${[['Mã căn hộ','VTV.4-0802'],['Loại','2PN+'],['Diện tích căn (m²)','132'],['Diện tích tính phí (m²)','125'],['Dự án','Victoria Village'],['Phân khu/Tháp','T4'],['Project address','Hương Lộ 2, xã Long Hưng, TP Biên Hòa, Tỉnh Đồng Nai, Việt Nam']].map(x=>`<div><label>${x[0]}</label><b>${x[1]}</b></div>`).join('')}</div>`)}
function unitHandover(){return `<article class="unit-section unit-handover"><h3>Bàn giao<span>⌃</span></h3><div class="unit-fields">${[['Loại hình bàn giao','Bàn giao thô'],['Ngày ký HĐMB','16/01/2024'],['Ngày nghiệm thu với tổng thầu (TOC)','02/02/2025'],['Ngày bàn giao','20/06/2025'],['Ngày bắt đầu tính phí','20/06/2025'],['Giấy chứng nhận quyền sở hữu',`Số: 1234567978<br><a>${icon("attachment-file.svg")}Tập đính kèm</a>`],['Ngày cấp/sang quyền CNQSH','02/02/0226']].map(x=>`<div><label>${x[0]}</label><b>${x[1]}</b></div>`).join('')}</div></article>`}
function unitOwners(){return unitSection('Chủ sở hữu',`<div class="unit-fields owners">${[['Chủ sở hữu','Trần Văn Nhân'],['Số GTTT','CCCD: ********8987'],['Số ĐT đăng ký HĐMB','********989'],['Email đăng ký HĐMB','nhantv@gmail.com'],['Đồng sở hữu','Hoàng Thu Trang'],['Số GTTT','CCCD: ********8444'],['Số ĐT','********888'],['Email','tranght@gmail.com']].map(x=>`<div><label>${x[0]}</label><b class="${x[1].includes('*')?'masked-value':''}">${x[1]}</b></div>`).join('')}</div>`)}
function simpleUnitTable(title,rows){const cell=x=>{const value=String(x),content=x==='Tài liệu đính kèm'?`<div class="attachment-thumbs"><img src="${A}login-city.png"><img src="${A}screens/Unit detail.png"><span><img src="${A}screens/Building list - PM role.png"><b>+4</b></span></div>`:value.endsWith('.pdf')?`<span class="file-link">${icon('attachment-file.svg')}${value}</span>`:value;return `<td class="${value.includes('*')?'masked-value':''}">${content}</td>`};return unitSection(title,`<table class="unit-mini-table ${title==='Chính sách bán hàng'?'sales-policy-table':''}">${rows.map(r=>`<tr>${r.map(cell).join('')}</tr>`).join('')}</table>`)}
function unitDocuments(){const rows=[['Trần Văn Nhân','Giấy chứng nhận quyền<br>sở hữu','20/03/2025','Kitchen Hygiene SOP','20/03/2025'],['Trần Văn Nhân','Lỗi bàn giao nhà','20/03/2025','VTV.4-0802_defect','20/03/2025'],['Phạm Quỳnh Như','Hợp đồng thuê nhà','26/05/2025-26/05/2026','Hopdongthuenha','20/03/2025']];return unitSection('Tài liệu căn hộ (3)',`<table class="unit-mini-table document-table"><thead><tr>${['Người tạo','Loại Tài Liệu','Thời gian hiệu lực','Link tài liệu','Ngày tạo'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td><a>${icon('pdf.svg')}${r[3]}</a></td><td>${r[4]}</td></tr>`).join('')}</tbody></table>`)}
function unitServices(){const rows=[['00012345','Phạm Thùy Linh','Chủ hộ','Đăng ký xe','Đang chờ duyệt','CSKH duyệt','CSKH','23/05/2025'],['00035791','Lương Thùy Hằng','Thành viên gia đình','Sửa chữa','Khởi tạo','CSKH duyệt','Kế toán','23/05/2025'],['00057913','Trần Văn Nam','Chủ thuê','Phản ánh','Đã hoàn thành','CSKH duyệt','Kỹ thuật','23/05/2025'],['00068024','Đào Thùy Linh','Chủ hộ','Đăng ký tiện ích','Đang xử lý','Chủ hộ duyệt','Quản lý','23/05/2025']];return unitSection('Yêu cầu dịch vụ',`<div class="service-table-wrap"><table class="unit-mini-table service-table"><thead><tr>${['Mã yêu cầu','Người yêu cầu','Loại yêu cầu','Trạng thái','Giai đoạn','Phụ trách','Thời hạn hoàn thành'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b><small>${r[2]}</small></td><td>${r[3]}</td><td><span class="service-state s${i}">${r[4]}</span></td><td>${r[5]}</td><td>${r[6]}</td><td>${r[7]}</td></tr>`).join('')}</tbody></table></div>`)}
function unitRentals(){const rows=[['Hợp đồng thuê.pdf','Phạm Quỳnh Như','******1285','26/05/2024 - 26/05/2025','30/05/2025'],['Hợp đồng thuê_2024.pdf','Lưu Thanh Hương','******1607','12/04/2023 - 12/04/2024','30/4/2026'],['','Phạm Quỳnh Như','******1607','10/03/2022 - 10/03/2023','30/4/2022']];return unitSection('Thông tin thuê',`<table class="unit-mini-table rental-table"><thead><tr>${['Hợp đồng thuê','Cư dân','Số điện thoại liên hệ','Thời hạn hiệu lực hợp đồng','Ngày cập nhật'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i<2?`<a class="file-link">${icon('attachment-file.svg')}${r[0]}</a>`:`<div class="attachment-thumbs"><img src="${A}login-city.png"><img src="${A}screens/Unit detail.png"><span><img src="${A}screens/Building list - PM role.png"><b>+4</b></span></div>`}</td><td><b>${r[1]}</b><small>Chủ thuê</small></td><td><span class="masked-value">${r[2]}</span>${i===0?'<i class="more-phone">+1</i>':''}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('')}</tbody></table>`)}
function unitHistory(){const rows=['Tạo mới căn hộ VTV.4-0802','Cập nhật thông tin chủ sở hữu','Cập nhật hợp đồng thuê #HD-2024-001','Bàn giao căn hộ cho khách hàng','Thay đổi trạng thái: Đang vận hành','Huỷ yêu cầu bảo trì #YC-0045'];return unitSection('Lịch sử hoạt động',`<div class="history-list">${rows.map((x,i)=>`<div><i></i><small>${['15/03/2024 09:30','20/03/2024 14:15','01/04/2024 10:00','15/05/2024 08:00','16/05/2024 09:00','20/06/2024 11:30'][i]}</small><b>${x}</b><span>${i%2?'Trần Thị B':'Nguyễn Văn A'}</span></div>`).join('')}</div>`)}
function render(){let r=location.hash.slice(1)||'login';if(r==='login')projectMenuOpen=false;const views={login,dashboard:()=>dashboard(false),investor:()=>dashboard(true),projects:projectList,buildings:buildingList,handover:handoverList,'handover-detail':handoverDetail,'handover-team':handoverTeamTab,'handover-schedule':handoverScheduleTab,'handover-email':handoverEmailTab,'handover-form':handoverFormTab,'handover-notifications':handoverNotifications,'create-notification':createHandoverNotification,'handover-plan':handoverPlan,'handover-plan-detail':handoverPlanDetail,units,project:projectDetail,unit:unitDetail,'create-project':createProject,'new-project':newProject,'import-preview':importPreview,'import-result':importResult};if(!views[r])r='dashboard';document.querySelector('#app').innerHTML=views[r]();const language=document.querySelector('.language');if(language)language.innerHTML=`${icon('globe.svg')}<b>Tiếng Việt</b>${icon('expand-more.svg')}`;document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));document.querySelector('#login')?.addEventListener('submit',e=>{e.preventDefault();go('dashboard')});document.querySelector('.ms')?.addEventListener('click',()=>go('dashboard'));document.querySelector('.hamb')?.addEventListener('click',()=>document.querySelector('.side').classList.toggle('open'));document.querySelector('.new-project')?.addEventListener('click',()=>go('new-project'));document.querySelector('.import-project')?.addEventListener('click',()=>{document.body.insertAdjacentHTML('beforeend',importModal());bindImport()});document.querySelectorAll('.save-project').forEach(x=>x.onclick=()=>go('projects'))}
function bindImport(){document.querySelectorAll('.close-import').forEach(x=>x.onclick=()=>document.querySelector('.import-overlay')?.remove());const input=document.querySelector('#excel-file'),name=document.querySelector('#import-name'),next=document.querySelector('.continue-import'),drop=document.querySelector('.drop-zone');let hasFile=false;const validate=()=>next.disabled=!(hasFile&&name.value.trim());const selected=fileName=>{hasFile=true;drop.querySelector('span').innerHTML=`Đã chọn: <b>${fileName}</b>`;validate()};name.oninput=validate;input.onchange=()=>input.files.length&&selected(input.files[0].name);drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');if(e.dataTransfer.files.length)selected(e.dataTransfer.files[0].name)};next.onclick=()=>{document.querySelector('.import-overlay')?.remove();go('create-project')}}
document.addEventListener('click',e=>{
  const planCalendar=e.target.closest('.plan-modal-fields label>span img');
  if(planCalendar){
    const picker=planCalendar.parentElement.querySelector('.handover-date-picker');
    if(picker?.showPicker)picker.showPicker();else picker?.focus();
    return;
  }
  const createBatch=e.target.closest('.create-handover');
  if(createBatch&&location.hash==='#handover'){
    document.body.insertAdjacentHTML('beforeend',handoverPlanModal());
    return;
  }
  if(e.target.closest('.close-handover-plan')){
    document.querySelector('.handover-plan-overlay')?.remove();
    return;
  }
  if(e.target.closest('.handover-plan-next')){
    document.querySelector('.handover-plan-overlay')?.remove();
    go('handover-plan');
    return;
  }
  const menuTrigger=e.target.closest('.batch-menu-trigger');
  if(menuTrigger){
    e.stopPropagation();
    const menu=menuTrigger.parentElement.querySelector('.batch-dropdown');
    document.querySelectorAll('.batch-dropdown.open').forEach(x=>{if(x!==menu)x.classList.remove('open')});
    menu?.classList.toggle('open');
    return;
  }
  const menuOption=e.target.closest('.batch-dropdown button');
  if(menuOption){
    const menu=menuOption.closest('.batch-dropdown');
    menu.querySelectorAll('button').forEach(x=>{x.classList.remove('selected');x.querySelector('span')?.remove()});
    menuOption.classList.add('selected');
    menu.classList.remove('open');
    return;
  }
  document.querySelectorAll('.batch-dropdown.open').forEach(x=>x.classList.remove('open'));
  if(!e.target.matches('.field .eye'))return;
  const input=e.target.closest('.field')?.querySelector('input');
  if(input)input.type=input.type==='password'?'text':'password';
});
function showPlanFile(file){const drop=document.querySelector('.plan-drop'),name=drop?.querySelector('.plan-file-name');if(!drop||!name||!file)return;name.textContent=file.name;drop.classList.add('has-file')}
document.addEventListener('change',e=>{
  if(e.target.matches('.plan-file-input')&&e.target.files?.[0])showPlanFile(e.target.files[0]);
  const table=e.target.closest('.new-detail-table');
  if(!table||!e.target.matches('.select-all-units,.select-unit'))return;
  const selectAll=table.querySelector('.select-all-units');
  const units=[...table.querySelectorAll('.select-unit')];
  if(e.target===selectAll)units.forEach(unit=>unit.checked=selectAll.checked);
  const selected=units.filter(unit=>unit.checked).length;
  selectAll.checked=selected===units.length&&units.length>0;
  selectAll.indeterminate=selected>0&&selected<units.length;
});
document.addEventListener('dragover',e=>{const drop=e.target.closest('.plan-drop');if(!drop)return;e.preventDefault();drop.classList.add('dragging')});
document.addEventListener('dragleave',e=>e.target.closest('.plan-drop')?.classList.remove('dragging'));
document.addEventListener('drop',e=>{const drop=e.target.closest('.plan-drop');if(!drop)return;e.preventDefault();drop.classList.remove('dragging');const file=e.dataTransfer?.files?.[0];if(file){const input=drop.querySelector('.plan-file-input');try{const transfer=new DataTransfer();transfer.items.add(file);input.files=transfer.files}catch{}showPlanFile(file)}});
function syncPlanDetailHeader(){const route=location.hash,crumb=document.querySelector('.header-crumb b');if(route==='#create-notification'){if(crumb)crumb.textContent='Tạo thông báo';return}if(route!=='#handover-plan-detail')return;const name=document.querySelector('.profile strong'),role=document.querySelector('.profile span');if(name)name.textContent='Peter Nguyễn';if(role)role.textContent='PMD';if(crumb)crumb.textContent='Lập kế hoạch BG'}
addEventListener('hashchange',render);addEventListener('hashchange',syncPlanDetailHeader);render();syncPlanDetailHeader();
